[package]
name = "clawtype-chords"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
const_map.workspace = true
clawtype-macros.workspace = true

