[workspace]
resolver = "2"
members = ["main"]

[workspace.package]
authors = ["Mateusz Czapliński <czapkofan@gmail.com>"]
license = "AGPL-3.0-or-later"
edition = "2021"

[workspace.dependencies]
embassy-executor = { version = "0.7.0", features = ["task-arena-size-4096", "arch-cortex-m", "executor-thread", "executor-interrupt"] }
embassy-time = { version = "0.4.0" }
embassy-nrf = { version = "0.3.1", features = ["nrf51", "time-driver-rtc1", "time", "rt"] }

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7"
panic-halt = { version = "1.0.0" }

[profile.release]
debug = 2
opt-level = "z"
lto = true

